##服务器配置
server:
  port: 7171

## dubbo相关配置
dubbo:
  application:
    name: member
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20880